### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by Mat-byte** [sap-tutorials/Issues#707]
Tutorial: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html#9c3c20cd-f21b-438b-9029-34ff7adc1549

Hi, Can you support me with my issue?
I did all the tutorial and the port5000 response:
![image](https://user-images.githubusercontent.com/58303881/191817496-20ce006e-3827-4016-af05-81372cc563f0.png)

This is my configuration:
![image](https://user-images.githubusercontent.com/58303881/191817604-c1f41a97-ca32-4534-9c7e-34aa609c804d.png)

Also, the link with cf looks good:
![image](https://user-images.githubusercontent.com/58303881/191817751-c97412fc-2611-4bc8-a7dd-9b2e93832d05.png)

Thanks in advance-

**Comment by jung-thomas** [comment]
If you add the path (/interaction_items/webapp/index.html) to the URL that opens - does that work?

**Comment by Mat-byte** [comment]
Hi @jung-thomas , thanks for the quickly reply. It doesn't work. 
It's weird because if I add /user-api/attributes it shows me :
![image](https://user-images.githubusercontent.com/58303881/191838545-ba1abd17-89ef-4d5d-bc1c-33f97a89520b.png)

**Comment by jung-thomas** [comment]
". It doesn't work."
Does it load the HTML page but give you an error on the service call?  Or do you continue to get the bad gateway message?

**Comment by Mat-byte** [comment]
I keep getting "Bad gateway" message

**Comment by jung-thomas** [comment]
Could you please share what's in your xs-app.json file in the /app folder.  

What I'm confused by: your application router must be running and it is connected to the xsuaa correctly.  Otherwise, the call to the /user-api/attributes would fail.  I kind of assumed your connection between the application router and the CAP service was the issue. But in that situation, the HTML content from the Application Router would still load correctly but you would get an error message when calling the OData service.  Yet you are getting a Bad gateway when just trying to load static html content from the application router. Therefore it seems the issue has to be with the application router configuration still.

**Comment by Mat-byte** [comment]
Yes Jung, it must be the application router because when I run through the 4004 port, it open ok, and if I try to open the interactions_times it raise "Unauthorized" which is correct.
![image](https://user-images.githubusercontent.com/58303881/191841069-f53fe31e-8d14-46ed-9a90-497442e18f14.png)

**It is my xs-app.json:** 
![image](https://user-images.githubusercontent.com/58303881/191841592-08459a38-29cd-4e82-be38-0e26cd208d18.png)

**Comment by Mat-byte** [comment]
Hi @jung-thomas , it's my repository in case it can give you more information:
https://github.com/Mat-byte/CAP-HANACloud

Thanks!

**Comment by jung-thomas** [comment]
There's nothing wrong with the code or configuration in your project.  I took your project from GitHub and cloned it into my workspace.  I then ran the cds bind to my existing service instances.
![image](https://user-images.githubusercontent.com/12159356/192008620-da9a99a8-50c6-4efa-9084-4d2242694360.png)

I recreated the default-env.json in the /app folder (because that is filtered out of git commits).  

I then run your app without any other changes and it works perfectly fine. 
![image](https://user-images.githubusercontent.com/12159356/192008741-5bc91716-4626-45be-b71f-3cca7adf8355.png)

The ONLY thing that I can see that is different is that I'm using the Free Tier and you are using the Trial.  I don't know if there is some technical limitation of the trial that's stopping this from working.  That's about all I can think of at this point. Or some bug in BAS itself that's only in the trial landscape but not the production landscape (free tier is production landscape - trial has its own separate landscape). 

I'm curious when you do Help->About in the Business Application Studio -- what version is shown?  Here is mine:
![image](https://user-images.githubusercontent.com/12159356/192009734-0ca5c063-2619-44b0-8e65-0436ba804fd4.png)

**Comment by ubheamar** [comment]
I was also facing this issue. but its working fine now.
I am using 2 command prompt to run application
1 command :  npm run app:run
package.json script
"app": "npm start --prefix app",
"app:run": "cds bind --exec npm run app",
2.command prompt: npm run watch-hybrid
package.json script
 "watch-hybrid": "cds watch --profile hybrid",

@jung-thomas is this correct way to run it?

**Comment by jung-thomas** [comment]
Yes it is actually required to use two command prompts. Both the CAP Service and the App Router have to be running at the same time for this to work. They are two separate applications.

**Comment by Mat-byte** [comment]
I tried what Ubheamar recommends but it didn't work.

It is my version:
![image](https://user-images.githubusercontent.com/58303881/192046799-bee70c03-1477-4f14-807c-3be03f39f844.png)

Something to add:
This is my app/default-env.json...Should this file have something else? 
![image](https://user-images.githubusercontent.com/58303881/192048280-f3cd63a1-3772-40db-b289-32758ae706a1.png)

The "VCAP_SERVICES" was something that I added because I saw it on a SAP video. If I delete that part and run again npm install inside app folder, and then run cds bind --exec...... Now it work:
![image](https://user-images.githubusercontent.com/58303881/192048913-66280631-608e-4100-9296-485416f88586.png)

But if I try to open Interactions_Headers it is shown :
![image](https://user-images.githubusercontent.com/58303881/192049140-87aad492-7c2b-40f3-b6a7-6a2eeeb4e4dd.png)

It's very confusing because I follow the tutorial step by step. 
Any advice will be appreciated.

**Comment by jung-thomas** [comment]
No you don't need the VCAP_SERVICES section in the default-env.json.  
The acquiring client from the pool is a different message than what you were saying earlier. That probably means you can't connect to your HANA DB.  Remember in both trial and free tier that HANA is shut down every night automatically. You have to manually restart it each day.

**Comment by Mat-byte** [comment]
Now it's working.  My bad.
Thank you Jung.
